[tool.poetry]
name = "cs121-whales"
version = "1.0.0"
description = "Chess AI web application using minimax and deep learning on backend"
authors = ["Ben Baral", "Shannon Collier", "Miles President", "Radon Rosborough", "Max Treutelaar"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11, <4.0"
black = "^26.5.1"
Flask = "^3.1.3"
flask-talisman = "^1.1.0"
gunicorn = "^26.0.0"
chess = "^1.11.2"
onnxruntime = "^1.26.0"
onnx = "^1.21.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
