#!/usr/bin/env bash

set -e
set -o pipefail

function fail {
    (
        cat
        echo
        echo "To work around the problem temporarily, commit with -n."
    ) 1>&2
    exit 1
}

if ! command -v lint-staged &>/dev/null; then
    fail <<EOF
Please install lint-staged first.
For example:

    $ yarn global add lint-staged
EOF
fi

if ! command -v pipenv &>/dev/null; then
    fail <<EOF
Please install Pipenv first.
For example:

    $ brew install pipenv
    $ sudo pacman -S python-pipenv
    $ pip3 install pipenv
EOF
fi

if ! venv="$(PIPENV_IGNORE_VIRTUALENVS=1 pipenv --venv)"; then
    fail <<EOF
Please create a virtualenv first.
For example:

    $ pipenv install --python /path/to/python3.6
EOF
fi

if [[ ! -x "$venv/bin/black" ]]; then
    fail <<EOF
Please update your virtualenv first.
For example:

    $ pipenv install
EOF
fi

if ! command -v prettier &>/dev/null; then
    fail <<EOF
Please install Prettier first.
For example:

     $ brew install prettier
     $ sudo pacman -S prettier
     $ yarn global add prettier
EOF
fi

if [[ -n "$WHALES_NO_TTY" ]]; then
    lint-staged | cat
else
    lint-staged
fi
